import type { ComponentDefinition } from "@/types/nodes";

export const componentRegistry: Record<string, ComponentDefinition> = {
  terminal: {
    type: "terminal",
    label: "Terminal",
    description: "A shell terminal that accepts commands",
    icon: "Terminal",
    category: "basics",
    defaultConfig: { shell: "/bin/bash" },
    configFields: [
      { key: "shell", label: "Shell", type: "select", options: ["/bin/bash", "/bin/sh", "/bin/zsh"] },
    ],
  },
  command: {
    type: "command",
    label: "Command",
    description: "A shell command to execute",
    icon: "Code",
    category: "basics",
    defaultConfig: { command: "", args: "" },
    configFields: [
      { key: "command", label: "Command", type: "text", placeholder: "ls", required: true },
      { key: "args", label: "Arguments", type: "text", placeholder: "-la" },
    ],
  },
  process: {
    type: "process",
    label: "Process",
    description: "A running process on the system",
    icon: "Cpu",
    category: "basics",
    defaultConfig: { name: "", pid: "" },
    configFields: [
      { key: "name", label: "Process Name", type: "text", placeholder: "nginx", required: true },
      { key: "pid", label: "PID", type: "text", placeholder: "1234" },
    ],
  },
  port: {
    type: "port",
    label: "Port",
    description: "A network port",
    icon: "Plug",
    category: "basics",
    defaultConfig: { port: 8080, protocol: "TCP" },
    configFields: [
      { key: "port", label: "Port Number", type: "number", required: true },
      { key: "protocol", label: "Protocol", type: "select", options: ["TCP", "UDP"] },
    ],
  },
  container: {
    type: "container",
    label: "Container",
    description: "A Docker container running an image",
    icon: "Box",
    category: "docker",
    defaultConfig: { image: "", port: 80, env: "" },
    configFields: [
      { key: "image", label: "Image", type: "text", placeholder: "nginx:latest", required: true },
      { key: "port", label: "Container Port", type: "number" },
      { key: "env", label: "Environment", type: "textarea", placeholder: "KEY=value" },
    ],
  },
  image: {
    type: "image",
    label: "Image",
    description: "A Docker image",
    icon: "Layers",
    category: "docker",
    defaultConfig: { tag: "latest", registry: "docker.io" },
    configFields: [
      { key: "tag", label: "Tag", type: "text", placeholder: "latest" },
      { key: "registry", label: "Registry", type: "text", placeholder: "docker.io" },
    ],
  },
  volume: {
    type: "volume",
    label: "Volume",
    description: "A storage volume mount",
    icon: "HardDrive",
    category: "docker",
    defaultConfig: { name: "", mountPath: "", hostPath: "" },
    configFields: [
      { key: "name", label: "Volume Name", type: "text", required: true },
      { key: "mountPath", label: "Mount Path", type: "text", placeholder: "/data" },
      { key: "hostPath", label: "Host Path", type: "text", placeholder: "/host/data" },
    ],
  },
  pod: {
    type: "pod",
    label: "Pod",
    description: "A Kubernetes Pod - the smallest deployable unit",
    icon: "Hexagon",
    category: "kubernetes",
    defaultConfig: { name: "", labels: "app=myapp", replicas: 1 },
    configFields: [
      { key: "name", label: "Pod Name", type: "text", placeholder: "web-pod", required: true },
      { key: "labels", label: "Labels", type: "text", placeholder: "app=myapp" },
    ],
  },
  deployment: {
    type: "deployment",
    label: "Deployment",
    description: "A Kubernetes Deployment managing Pod replicas",
    icon: "GitBranch",
    category: "kubernetes",
    defaultConfig: { name: "", replicas: 2, selector: "app=myapp", image: "", port: 80 },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "web-deployment", required: true },
      { key: "replicas", label: "Replicas", type: "number", required: true },
      { key: "selector", label: "Selector", type: "text", placeholder: "app=myapp" },
      { key: "image", label: "Image", type: "text", placeholder: "nginx:latest", required: true },
      { key: "port", label: "Container Port", type: "number" },
    ],
  },
  service: {
    type: "service",
    label: "Service",
    description: "A Kubernetes Service providing network access to Pods",
    icon: "Globe",
    category: "kubernetes",
    defaultConfig: { name: "", type: "ClusterIP", port: 80, targetPort: 80, selector: "app=myapp" },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "web-service", required: true },
      { key: "type", label: "Service Type", type: "select", options: ["ClusterIP", "NodePort", "LoadBalancer"] },
      { key: "port", label: "Port", type: "number", required: true },
      { key: "targetPort", label: "Target Port", type: "number", required: true },
      { key: "selector", label: "Selector", type: "text", placeholder: "app=myapp", required: true },
    ],
  },
  ingress: {
    type: "ingress",
    label: "Ingress",
    description: "A Kubernetes Ingress for HTTP routing",
    icon: "ArrowRightLeft",
    category: "kubernetes",
    defaultConfig: { name: "", host: "", path: "/", serviceName: "", servicePort: 80 },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "host", label: "Host", type: "text", placeholder: "example.com" },
      { key: "path", label: "Path", type: "text", placeholder: "/" },
      { key: "serviceName", label: "Service Name", type: "text", required: true },
      { key: "servicePort", label: "Service Port", type: "number" },
    ],
  },
  configmap: {
    type: "configmap",
    label: "ConfigMap",
    description: "A Kubernetes ConfigMap for configuration data",
    icon: "FileText",
    category: "kubernetes",
    defaultConfig: { name: "", data: "" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "data", label: "Data (key=value)", type: "textarea", placeholder: "DB_HOST=localhost" },
    ],
  },
  secret: {
    type: "secret",
    label: "Secret",
    description: "A Kubernetes Secret for sensitive data",
    icon: "Lock",
    category: "kubernetes",
    defaultConfig: { name: "", data: "" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "data", label: "Data (key=value)", type: "textarea", placeholder: "DB_PASSWORD=secret" },
    ],
  },
  pv: {
    type: "pv",
    label: "PersistentVolume",
    description: "A Kubernetes PersistentVolume",
    icon: "Database",
    category: "kubernetes",
    defaultConfig: { name: "", capacity: "1Gi", accessMode: "ReadWriteOnce" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "capacity", label: "Capacity", type: "text", placeholder: "1Gi" },
      { key: "accessMode", label: "Access Mode", type: "select", options: ["ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany"] },
    ],
  },
  pvc: {
    type: "pvc",
    label: "PersistentVolumeClaim",
    description: "A Kubernetes PersistentVolumeClaim",
    icon: "DatabaseZap",
    category: "kubernetes",
    defaultConfig: { name: "", request: "1Gi", accessMode: "ReadWriteOnce" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "request", label: "Storage Request", type: "text", placeholder: "1Gi" },
      { key: "accessMode", label: "Access Mode", type: "select", options: ["ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany"] },
    ],
  },
  loadbalancer: {
    type: "loadbalancer",
    label: "Load Balancer",
    description: "Distributes traffic across targets",
    icon: "Network",
    category: "orchestration",
    defaultConfig: { name: "", algorithm: "round-robin" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "algorithm", label: "Algorithm", type: "select", options: ["round-robin", "least-connections", "ip-hash"] },
    ],
  },
  healthcheck: {
    type: "healthcheck",
    label: "Health Check",
    description: "Monitors the health of a service",
    icon: "HeartPulse",
    category: "orchestration",
    defaultConfig: { path: "/health", port: 80, interval: 30 },
    configFields: [
      { key: "path", label: "Path", type: "text", placeholder: "/health" },
      { key: "port", label: "Port", type: "number" },
      { key: "interval", label: "Interval (s)", type: "number" },
    ],
  },
  helmchart: {
    type: "helmchart",
    label: "Helm Chart",
    description: "A Helm Chart packaging K8s resources",
    icon: "Package",
    category: "helm",
    defaultConfig: { name: "", version: "1.0.0" },
    configFields: [
      { key: "name", label: "Chart Name", type: "text", required: true },
      { key: "version", label: "Version", type: "text", placeholder: "1.0.0" },
    ],
  },
  helmrelease: {
    type: "helmrelease",
    label: "Helm Release",
    description: "An installed instance of a Helm Chart",
    icon: "Rocket",
    category: "helm",
    defaultConfig: { name: "", chart: "", namespace: "default", values: "" },
    configFields: [
      { key: "name", label: "Release Name", type: "text", required: true },
      { key: "chart", label: "Chart", type: "text", required: true },
      { key: "namespace", label: "Namespace", type: "text", placeholder: "default" },
      { key: "values", label: "Values Override", type: "textarea" },
    ],
  },
  namespace: {
    type: "namespace",
    label: "Namespace",
    description: "A Kubernetes Namespace for isolating resources",
    icon: "FolderOpen",
    category: "kubernetes",
    defaultConfig: { name: "" },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "argocd", required: true },
    ],
  },
  serviceaccount: {
    type: "serviceaccount",
    label: "ServiceAccount",
    description: "A Kubernetes ServiceAccount for pod identity and API access",
    icon: "UserCheck",
    category: "kubernetes",
    defaultConfig: { name: "", namespace: "default" },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "argocd-server", required: true },
      { key: "namespace", label: "Namespace", type: "text", placeholder: "default" },
    ],
  },
  role: {
    type: "role",
    label: "Role",
    description: "A Kubernetes Role defining permissions within a namespace",
    icon: "Shield",
    category: "kubernetes",
    defaultConfig: { name: "", namespace: "", rules: "" },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "argocd-role", required: true },
      { key: "namespace", label: "Namespace", type: "text", placeholder: "argocd" },
      { key: "rules", label: "Rules (apiGroups/resources/verbs)", type: "textarea", placeholder: "apps: deployments: get,list,watch" },
    ],
  },
  rolebinding: {
    type: "rolebinding",
    label: "RoleBinding",
    description: "Binds a Role to subjects (ServiceAccounts, users, groups)",
    icon: "ShieldCheck",
    category: "kubernetes",
    defaultConfig: { name: "", namespace: "", roleName: "", subjects: "" },
    configFields: [
      { key: "name", label: "Name", type: "text", placeholder: "argocd-rolebinding", required: true },
      { key: "namespace", label: "Namespace", type: "text", placeholder: "argocd" },
      { key: "roleName", label: "Role Name", type: "text", placeholder: "argocd-role", required: true },
      { key: "subjects", label: "Subjects", type: "textarea", placeholder: "ServiceAccount: argocd-server" },
    ],
  },
  pulumistack: {
    type: "pulumistack",
    label: "Pulumi Stack",
    description: "A Pulumi stack for infrastructure",
    icon: "Blocks",
    category: "iac",
    defaultConfig: { name: "", runtime: "typescript" },
    configFields: [
      { key: "name", label: "Stack Name", type: "text", required: true },
      { key: "runtime", label: "Runtime", type: "select", options: ["typescript", "python", "go"] },
    ],
  },
  pulumiprovider: {
    type: "pulumiprovider",
    label: "Pulumi Provider",
    description: "A Pulumi cloud provider (AWS, GCP, Azure)",
    icon: "Cloud",
    category: "iac",
    defaultConfig: { name: "", provider: "aws" },
    configFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "provider", label: "Provider", type: "select", options: ["aws", "gcp", "azure", "kubernetes"] },
    ],
  },
};

export const categoryLabels: Record<string, string> = {
  basics: "Basics",
  docker: "Docker",
  orchestration: "Orchestration",
  kubernetes: "Kubernetes",
  helm: "Helm",
  iac: "Infrastructure as Code",
};

export function getComponentsForStage(componentTypes: string[]): ComponentDefinition[] {
  return componentTypes
    .map((t) => componentRegistry[t])
    .filter(Boolean);
}
